### ISSUE TITLE
TODO: Playerテーブルの拡張

### ISSUE THREAD

**Issue by monksoffunk** [scandamus/ft_transcendence#134]
### Playerに以下を追加
- 状況を示すstatusフィールドの追加
STATUS_CHOICES = [
        ('friend_match', 'フレンドマッチ中'),
        ('lounge_match', 'ラウンジマッチ中'),
        ('tournament_match', 'トーナメントマッチ中'),
        ('tournament', 'トーナメント中'),
        ('friend_waiting', 'フレンドマッチ待機中'),
        ('lounge_waiting', 'ラウンジマッチ待機中'),
        ('waiting', '待機中'),
    ]
- 下記の場合に設定するcurrent_match（Match FK）
        ('friend_match', 'フレンドマッチ中'),
        ('lounge_match', 'ラウンジマッチ中'),
        ('tournament_match', 'トーナメントマッチ中'),

### 用途
- [x] 試合中（フレンドマッチ、ラウンジマッチ、トーナメントマッチ中）にフレンドマッチを受けないようにする
- [x] フレンドマッチ待機中（モーダル表示中）に別のフレンドマッチを受けないようにする
- [x] ラウンジマッチ待機中（モーダル表示中）にフレンドマッチを受けないようにする
- [x] トーナメント中（トーナメントマッチではない待機中）はどうする？
- [x] 試合中に切断やリロードなどが発生した際、ログインし直し後にまだ試合が続いていれば試合に復帰する
- [ ] 試合中でもトーナメントマッチの場合のみ強制的に試合放棄の上、トーナメントマッチに遷移させる

**Comment by monksoffunk** [comment]
#137 マッチ待機中の多重マッチングを阻止

**Comment by monksoffunk** [comment]
#272に移行
